import Head from "next/head";
import styles from "../styles/Home.module.css";
import { DiscordLoginButton } from "react-social-login-buttons";
import { signIn, signOut, useSession } from "next-auth/react";
import Router from "next/router";
import Link from "next/link";
import { useState } from "react";
import Image from "next/image";

export default function Dashboard() {
  const { status, data } = useSession();
  const [deleting, setDeleting] = useState(false);
  if (status == "unauthenticated") {
    Router.push("/");
  }
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Matchmaking - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dashboard</h1>
      <div className="row w-100">
        <hr className="d-block d-md-none" />
        <div className="col-12 col-md-6">
          <h4>Tutorial</h4>
          <Link href="/tutorial">
            Tutorial for newcomers or for refresher purposes
          </Link>
          <br />
          We wont answer any questions you have unless you matched the tutorial.
          <br />
          <b>Note: </b>Tutorial was made in old versions of the site, but the
          concepts are still the same
        </div>
        <hr className="d-block d-md-none" />
        <div className="col-12 col-md-6">
          <h4>Matchmaking Actions</h4>
          <Link href="/form">Create/Edit Form</Link>
          <br />
          <Link href="/match">Matchmake yourself (Find your match)</Link>
        </div>
      </div>
      <hr />
      <h4>
        Logged in as {data?.user?.name}{" "}
        <Image
          src={data?.user?.image || ""}
          alt=""
          width={50}
          height={50}
          className="rounded-circle"
        />
      </h4>
      <div className={styles.buttonWrapper}>
        <br />
        <button
          style={{
            width: "200px",
          }}
          onClick={() => {
            signOut();
          }}
        >
          Logout
        </button>
        <button
          style={{
            width: "200px",
          }}
          onClick={async () => {
            if (deleting) return;
            setDeleting(true);
            const data = await fetch("/api/getResponse").then((res) =>
              res.json()
            );
            if (!data) {
              alert("Form is non-existant.");
            } else {
              await fetch("/api/delete")
                .then((res) => res.text())
                .then(() => {
                  alert("Form deleted.");
                })
                .catch(() => {
                  alert("Deleting form gave an error :(");
                });
            }
            setDeleting(false);
          }}
        >
          {deleting ? "Deleting..." : "Delete Form"}
        </button>
      </div>
    </div>
  );
}
