import Head from "next/head";
import styles from "../styles/Home.module.css";
import { DiscordLoginButton } from "react-social-login-buttons";
import { signIn, signOut, useSession } from "next-auth/react";
import Router from "next/router";
import Link from "next/link";
import { useState } from "react";

export default function Dashboard() {
  const { status, data } = useSession();
  const [deleting, setDeleting] = useState(false);
  if (status == "unauthenticated") {
    Router.push("/");
  }
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Matchmaking - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dashboard</h1>
      <br />
      <Link href="/tutorial">
        WATCH THIS TUTORIAL IF YOU ARE AN NEWCOMER OR IF YOU WANT AN
        REFRESHER!!!
      </Link>
      <br />
      <br />
      <Link href="/form">Create/Edit Form</Link>
      <br />
      <Link href="/match">Find your match!</Link>
      <div className={styles.buttonWrapper}>
        <button
          style={{
            width: "200px",
          }}
          onClick={() => {
            signOut();
          }}
        >
          Logout
        </button>
        <button
          style={{
            width: "200px",
          }}
          onClick={async () => {
            if (deleting) return;
            setDeleting(true);
            const data = await fetch("/api/getResponse").then((res) =>
              res.json()
            );
            if (!data) {
              alert("Form is non-existant.");
            } else {
              await fetch("/api/delete")
                .then((res) => res.text())
                .then(() => {
                  alert("Form deleted.");
                })
                .catch(() => {
                  alert("Deleting form gave an error :(");
                });
            }
            setDeleting(false);
          }}
        >
          {deleting ? "Deleting..." : "Delete Form"}
        </button>
      </div>
    </div>
  );
}
