import Head from 'next/head'
import styles from "../styles/Home.module.css"
import { DiscordLoginButton } from 'react-social-login-buttons'
import { signIn, useSession } from 'next-auth/react'
import Router from 'next/router'


export default function Home() {
  const { status } = useSession()
  if (status == "authenticated") {
    Router.push("/dashboard")
  }
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Matchmaking - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Login to continue</h1>
      <br />
      <div className={styles.buttonWrapper} >
        <DiscordLoginButton align='center' style={{
          width: "200px"
        }} onClick={() => { signIn("discord") }} />
      </div>

    </div>
  )
}
