import Head from "next/head";
import styles from "../styles/Home.module.css";
import { DiscordLoginButton } from "react-social-login-buttons";
import { signIn, useSession } from "next-auth/react";
import Router from "next/router";

export default function Home() {
  const { status } = useSession();
  if (status == "authenticated") {
    Router.push("/dashboard");
    return <></>;
  }
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Matchmaking - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Matchmaking. Refined. Accurate. Reliable.</h1>
      <div>
        Tired of old form matchmaking?
        <br />
        Tired of a month of waiting?
        <br />
        Well, if you are already a member of my discord server, that great
        matchmaking is HERE.
        <br />
        If not this won't do you much good, cuz only my discord server members
        can make use of this.
        <br />
        <button
          onClick={() => {
            signIn("discord");
          }}
        >
          Get Started
        </button>
      </div>
    </div>
  );
}
