import Head from "next/head";
import styles from "../styles/Home.module.css";
import { DiscordLoginButton } from "react-social-login-buttons";
import { signIn, signOut, useSession } from "next-auth/react";
import Router from "next/router";
import Link from "next/link";

export default function Dashboard() {
  const { status, data } = useSession();
  if (status == "unauthenticated") {
    Router.push("/");
  }
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Successful Submission!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Form submitted.</h1>
      <br />
      <Link href="/dashboard">Return to dashboard</Link>
    </div>
  );
}
