import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import Router from "next/router";
import Link from "next/link";

export default function Dashboard() {
  const { status, data } = useSession();
  if (status == "unauthenticated") {
    signIn("discord");
    return <></>;
  }
  return (
    <>
      <Head>
        <title>Successful Submission!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Form submitted.</h1>
      <hr />
      <Link href="/match" className="link-primary">
        Find a match
      </Link>
      <br />
      You'll want to click this, because you go straight to matchmaking youself,
      since this is an self matchmaking thingy.
      <br />
      <hr />
      <Link href="/dashboard" className="link-primary">
        Return to dashboard
      </Link>
      <br />
      Remember, no one matchmakes for you, except for yourself. Only click the
      button if you are busy or something.
      <hr />
    </>
  );
}
