import Head from "next/head";
import { useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const { status } = useSession();
  return (
    <>
      <Head>
        <title>Matchmaking - Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Tutorial (Scroll down when finished)</h1>
      <iframe
        src="https://streamable.com/e/ub0d63?autoplay=1&loop=0"
        allowFullScreen
        allow="autoplay"
        style={{
          width: "98vw",
          height: "54vw",
          overflow: "hidden",
          margin: "none",
        }}
      ></iframe>
      <br />
      <Link href="/dashboard">Return Home</Link>
      <br />
      <br />
    </>
  );
}
